name: Publish API docs to GitHub Pages, powered by Retype
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish API docs to GitHub Pages

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: retypeapp/action-build@latest

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
