name: Publish API docs

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "docs/**"

jobs:
  publish:
    name: Publish API docs to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with Retype
        uses: retypeapp/action-build@latest

      - name: Publish to GitHub Pages
        uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
